### ISSUE TITLE
Search results page

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#107]

**Comment by robgpeak** [comment]
I am assuming the search result will display the "Store Box", the same way it would as if the store box was shown to a user in a category section.

Having said that, I think we need to constrain the size of the box to have a maximum width and height of some uniformed size because it is likely it might be the only item that shows up in the search results.

I have mocked up a page to show the layout I would like to see, and there are two sticky notes with additional direction... https://app.moqups.com/robg/QSDVx2F07W/edit/page/a1819d6ea

**Comment by Dwells7583** [comment]
Updated. @ChrisASearles Can you take a look at the containing div. Having an issue when adding the class content container.

**Comment by Dwells7583** [comment]
@cgladue need you to in and add the similar stores and featured stores on the search page as well.  It is mocked up currently with dummy deals.

**Comment by cgladue** [comment]
ok, i will @robgpeak this means you will have to manually assign stores as "similar to" other stores in the backend, on a as yet to be created page, you ok with that ?

**Comment by robgpeak** [comment]
I left a sticky note on the mockup about that, but basically I would just use stores that are in the same category.  And maybe for a bit more clarity, it would use an algorithm something like this:

If the Search Result is a store that is only in one category, "Similar Stores" would be the first (top) 8 in the order listed in Advertiser Categories.  If the Searched results store is one of those 8, don't show it again in the Similar Stores section, skip it and still display 8 stores, but without the search resulted store(s) in the list.

If the search results yields a store that is in multiple categories, punt...  JK

In that instance, shit this gets a little tricky...  Before I even attempt to solve that, let's pose a couple of questions...

1. IS it possible to have the search function auto complete, or start filling in all the suggestions when someone starts typing?  If it is too complicated, maybe that is something table for a future release.  But if it is easy enough, and we did something like that, then instead of leading to a search results page, it would lead directly to a stores index page, because it would be obvious that it was what the person was looking for.

2. Not really a question, but more of an observation...  If someone types in "mac", (have a look at the results), are they looking for a computer, or makeup, or did they not complete Macys...?  In either case, the results yield several companies across multiple categories, and Similar stores is just a guess.

Looking at ebates, they autocomplete, and lead directly to the store's index page...  Looking at shop.retailbenefits.com they return store boxes, and some potentially relevant deals, but only use similar stores when you drill into a stores index page...

Realistically, this type of data (current lists of all active advertisers) is something we would need for the development of the browsers extensions anyway...

Sorry if this post raised more questions than it answered.

**Comment by cgladue** [comment]
how about this rob, we keep a counter of the # of times each advertiser is viewed, and for the similar stores we pull the top x advertisers based on # of views from within the same categories that the result is a member of...  if theres 10 search results that means there could be x * # of results displayed as similar

**Comment by robgpeak** [comment]
Thats fine.  The only thing is, for the number of similar stores that we want to display at any given time, I would only show 8 store boxes, and then have a More Link OR, a pagination thing that someone could click in the page number, or the next arrow.  Similar to what you have at the bottom right of all the back end pages that have lists of records.

**Comment by ChrisASearles** [comment]
@cgladue what's the status on this?

**Comment by cgladue** [comment]
@ChrisASearles SimilarStores is a property on the advertiser, so each advertiser will return a list of similar advertisers based on its category

**Comment by ChrisASearles** [comment]
Blocked pending a fix to #148

**Comment by ChrisASearles** [comment]
Committed.

**Comment by cgladue** [comment]
@robgpeak Published

**Comment by robgpeak** [comment]
Structure and layout of the page look pretty cool, but obviously the functionality of the "You might also like" section is not perfected yet, as the results that are showing up there, and particularly the "points/$" for each advertiser are not accurate.

I would also consider using the exact same look and functionality of the Feature Stores section on the home page to the right of the hero image for consistency sake.  Meaning, include the logo and same size font as you use on the home page.

So I am not sure if I should close this one?
