### ISSUE TITLE
Store Detail Page

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#120]
This is the container on the Store Index page that contains three columns, and the contents of those columns from left to right are; (1) the Store Index Image, and below that, separated by 10px, the “x points/$”, (2) a vertical line 1pt wide set to 80% of the height, (3) the description of the store [text left justified], and a Shop Now Button below that [right justified but still have enough of a buffer from the right and bottom of the container]  See the mockup at https://app.moqups.com/robg/QSDVx2F07W/edit/page/ab309be6f

**Comment by ChrisASearles** [comment]
@robgpeak we took a little creative license based off your mock up and taking into account the way the site has progressed since then. We'll work on something closer to your original design.

@Dwells7583 I checked in a version that I think will accomplish goals across the board but it needs some work. Pull my changes and see what you can do to polish it up.

**Comment by robgpeak** [comment]
Please let me know when they are visible to me.

**Comment by Dwells7583** [comment]
I cleaned up the text on this page as well as a few issues stacking on mobile. I also updated the description text to expand. @ChrisASearles having an issue with the way the ellipses are added to the end of the truncated text.
