### ISSUE TITLE
Just saw a page with an unsecure SSL lock

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#202]
https://doverdowns.complinks.co/stores/index/5447

I looked at other pages that I've added new header images to like https://doverdowns.complinks.co/stores/index/6712 and https://doverdowns.complinks.co/stores/index/6789 and they are showing the secure lock icon.

Seems like it is only from the ones that I added new header images to yesterday.  Here is another one that I uploaded yesterday that is showing unsecure...  https://doverdowns.complinks.co/stores/index/5339

![uploads/785ec645-3d21-4836-92bb-15b92aecc892/Screen Shot 2017-06-09 at 10.05.03 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F785ec645-3d21-4836-92bb-15b92aecc892%2FScreen+Shot+2017-06-09+at+10.05.03+AM.png)

**Comment by cgladue** [comment]
its the advertisement on the right side at the very bottom, its loading a http:// instead of https:// image which is coming from CJ or LS.

![image](https://user-images.githubusercontent.com/7914133/26979837-3b11f340-4cfe-11e7-985a-9bdb751cdb7a.png)

let me take a look about always replacing http:// with https:// when i pull the url, hopefully they have both available otherwise it will not show up

**Comment by cgladue** [comment]
its available in https also, wonder why they didnt just use the https version, oh well:

https://www.awltovhc.com/image-8235261-10760351-1462979928000

**Comment by cgladue** [comment]
@robgpeak take a look now ?

**Comment by robgpeak** [comment]
cool
