### ISSUE TITLE
Completed shopping trip (Completed meaning ending with a purchase) not showing up in our back end as completed.

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#216]
@cgladue Shopping trip 694 and purchase that I made on 6/13/17 was posted in the LS report on the 14th, but it is not showing up in our back end as a completed transaction.

![uploads/2f816092-1f5d-493f-9386-74594e23f062/Screen Shot 2017-06-15 at 9.49.54 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F2f816092-1f5d-493f-9386-74594e23f062%2FScreen+Shot+2017-06-15+at+9.49.54+PM.png)

**Comment by robgpeak** [comment]
Hi @cgladue any feedback on this?

**Comment by cgladue** [comment]
Yep this is because this merchant reports in batches and not realtime, Linkshare for realtime transactions reports the transaction twice, once with "is_event" set to yes and once with it set to no, so i filtered to only act on the transactions on is_event = true .. but aparently for batch transactions is_event is always no, so i will change my logic to require is_event = true only with transaction_type = realtime, otherwise if transaction_type = batch then it wont even look at the event flag, ill have it fixed in a few minutes,.

**Comment by cgladue** [comment]
@robgpeak please take a look at your shopping trips and see if the total is correct now.
