### ISSUE TITLE
Google Analytics is not tracking real time reporting

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#229]
@ChrisASearles I just installed GA on the corporate site https://complinks.co and it is working fine.  I can see in real time reporting who is on the corporate site, but it does not work on the shop subdomain?

**Comment by ChrisASearles** [comment]
It's actually the opposite issue that you think it is ;-)

We haven't done anything with the other site so when we configured IP filters in your analytics data they were only applied to the shop site so that site is filtering out your IP address where the corporate site isn't.

I applied the filters to both sites now so you should no longer see real time on either from your home network. You should be able to test this by shutting the WiFi off on your phone and hitting either. I'm seeing real time data on the shop site right now.

**Comment by robgpeak** [comment]
Shit, I totally forgot.
