### ISSUE TITLE
Users should not be able to double dip

### ISSUE THREAD

**Issue by morganpeak** [ChrisASearles/CompLinks#230]
With the plethora of cashback and coupon sites out there now, we need to be able to find a way to not allow users to "double dip" say, with Ebates and us. I have a browser extension called Honey that searches the web for promo codes and coupons and applies them automatically (which ebates now does as well) and when I activate my Ebates cashback, Honey tells me that I can't use both. We need to be able to stop people from doing this on our end too in the future.

**Comment by ChrisASearles** [comment]
@morganpeak the message you're seeing is really a function of the app (Honey) just informing you that you won't get the promo code value because of what you're getting via the link you clicked in eBates. The affiliate handles the double-dipping aspect on their end by only allowing one valid cookie at a time, and it generally always goes to the last advertiser who served a link to that user (that they actually clicked on). Don't really think there's anything for us to be able to do here.
