### ISSUE TITLE
Redesign store detail page

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#29]
Detail and deals should load in a smaller column, with a new Similar Stores section / column on the right (below on mobile). Card styles should remain consistent based on content (store vs deal).

Need to pull similar store data for that section. For now the simplest approach would appear to be pull the top 4 stores from the primary category of the loaded store sorted by display order.

Reference: https://app.moqups.com/robg/QSDVx2F07W/edit/page/ab309be6f

**Comment by ChrisASearles** [comment]
Also, change "Rewards" title to "Deals and Promotions"

**Comment by Dwells7583** [comment]
@cgladue as per the moqups from @robgpeak , is there a expiration date and Coupon code that I can display on the deals and promotions. I tried using the End.date for the expiration but that did not seem to work, unless there was no expiration date on that specific store.

**Comment by cgladue** [comment]
startDate and endDate should be populated, if the advertiser does not
specify a start date i fill it in with 1/1/2017 and if they do not enter a
end date i enter 12/31/2020  if either of those dates are detected then it
shouldnt be shown on the website i would think, otherwise it can be shown,
the code will take some string manipulation to try and parse accuratly, in
the meantime just leave a spot for it at some point it will be a property
of the object.



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=chadgladue@gmail.com&idSignature=22>



Chad Gladue
*DevNull Technology, LLC*

**Comment by Dwells7583** [comment]
Hey @cgladue  I need to pull the category image for the header of the store detail page. I just have a placeholder mocked in there now.

**Comment by Dwells7583** [comment]
@cgladue I need similar stores as well.

**Comment by cgladue** [comment]
@robgpeak which category image should i pull if there are multiple categories for the store ?

**Comment by robgpeak** [comment]
Please have a look at #106.  If we can have the functionality on the Advertisers edit page of being able to put a specific image in there for each individual advertiser, that would be great, but I'd the field is blank (at the moment at least), I would NOT want it to come back as a broken image on the front end.

**Comment by cgladue** [comment]
added Advertiser.headerImageUrl which will be the uploaded photo if there is one or the category image if no uploaded photo.
