### ISSUE TITLE
Missing Advertiser Logos

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#87]
@cgladue I did some digging and see there are two reasons why we might be missing advertiser logos.

1. They signed up after we did our original scrape of all the logos.  Those, Morgan and I can fix manually.

2. Not really sure why this is happening, but they were in our original scrape file, but they are not showing up...  https://screencast.com/t/dmVW17C657v

**Comment by cgladue** [comment]
i may have failed to upload all of them, from the original scrape, the
upload utility to amazon was cludgey at the time for that # of files, and i
got errors in the middle of the upload and tried to resume where it left
off, i went back and thought i got them all but i must have missed some...

if you upload now they should be corrected... and going forward it will
kinda be a manual thing when theres a new advertiser i guess since stupid
CJ and LS dont give me a url to the logo :\

when you view the image and get the XML its because Amazon S3 (Cloud
storage) is saying the file dosnt exist,  the logos are stored on the
amazon S3 cloud so when the site gets busy and popular and we have 4 Web
servers the images are in 1 central location instead of being on each of
the 4 servers and having to manage the synchronization across those
servers..







  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=chadgladue@gmail.com&idSignature=22>



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Understood.  So we will just manage them all manually.

**Comment by cgladue** [comment]
@robgpeak is going to upload the missing advertiser logos
