### ISSUE TITLE
Create Alerts to display status messages on site

### ISSUE THREAD

**Issue by cgladue** [ChrisASearles/CompLinks#93]
Need an alet box for Success, Warning and Error status with an area for the message to be displayed, and a X to close and perhaps even an autohide if youd like.  This would need to be in the _Layout view so it was available for any page on the front end, would be triggered if TempData["success"] was != null, TempData["warning"] was != null or TempData["error"] was != null

**Comment by ChrisASearles** [comment]
@cgladue can you describe a specific use case?

**Comment by cgladue** [comment]
sure, but all use cases would be the same since the notification/alert would be generic and allow the text to be specified

but for example the manage profile page i created where you can change your password and update First/Last/ and mobile number, once they press save and it redirects back to that page there should be a banner/notification green in color for the success, yellow for a warning, and red for an error, containing a nice icon like a check, x or triangle icon and the return text that gets pulled from TempData["success"], ["warning"], or ["error"]

**Comment by ChrisASearles** [comment]
@Dwells7583 I created the framework for this and added it to the Layout. Code's sitting in Views/Shared/_Messages.cshtml

**Comment by robgpeak** [comment]
Actually, I just looked more closely at the functionality, and I wanted to reopen it, but as a low priority.

If a user attempts to put in a phone number that is not a full 10 digits, and clicks update info, it responds with "Profile Has Been Updated" and reverts the phone number back to 555-555-5555.  I would suppose it should return a yellow error saying this phone number field must be 10 digits. Similar to what happens when the email address is not entered in the proper format

On a side note, nice job with the (___) ___-____ formatting when someone starts typing.

Also, if it's not too much trouble, can we add a check box, for "Home" or "Mobile" next to the field for the phone number?  Would be nice to know for SMS purposes.

**Comment by robgpeak** [comment]
@ChrisASearles shit, just realized I reopened this, submitted another comment, but did not assign it to anyone, or change the status (It's still in Review).  What would be the standard protocol in this case?

**Comment by ChrisASearles** [comment]
The issue you’re having actually isn’t related to this ticket at all so if the messages are fine please close this out and submit a new issue for the phone number problem.
